services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "app_db"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s